services:
  db:
    image: postgres:16-alpine
    container_name: application-tracker-db
    restart: always
    environment:
      POSTGRES_DB: application_tracker
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-net

  backend:
    build:
      context: ./backend/application_tracker
      dockerfile: Dockerfile
    container_name: application-tracker-backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: application_tracker
      DB_USER: appuser
      DB_PASSWORD: secretpassword
    ports:
      - "8080:8080"
    networks:
      - app-net

  frontend:
    build:
      context: ./frontend/application_tracker
      dockerfile: Dockerfile
    container_name: application-tracker-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"   # http://localhost:4200
    networks:
      - app-net

networks:
  app-net:

volumes:
  db_data: